version: '2'
services:
    webapp:
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:5000
        entrypoint: dotnet StephenHellicar.Website.WebApp.dll
        expose:
        - "5000"
        restart: always
        working_dir: /app
        build: ./webapp
    webapi:
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:5000
        entrypoint: dotnet StephenHellicar.Website.WebAPI.dll
        working_dir: /api
        build: ./webapi
        expose:
        - "5000"
        restart: always

    proxy:
        build: ./nginx
        ports:
        - "80:80"
        - "443:443"
        restart: always
        depends_on:
        - webapp
        - webapi
        volumes:
        - certs:/etc/letsencrypt:ro
        - certs-data:/data/letsencrypt:ro
        - /etc/localtime:/etc/localtime:ro
volumes:
    certs:
        driver: local
    certs-data:
        driver: local

