version: '2'
services:
    webapp:
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:5000
        entrypoint: dotnet StephenHellicar.WebApplication.dll
        expose:
        - "5000"
        restart: always
        working_dir: /app
        build: ./webapp
    webapi:
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:5000
        entrypoint: dotnet StephenHellicar.WebAPI.dll
        working_dir: /api
        build: ./webapi
        expose:
        - "5000"
        restart: always

    proxy:
        build: ./nginx
        ports:
        - "80:80"
        - "443:443"
        restart: always
        depends_on:
        - webapp
        - webapi
        volumes:
        - /etc/letsencrypt/live/stephen-hellicar.com/fullchain.pem:/etc/letsencrypt/live/stephen-hellicar.com/fullchain.pem:ro
        - /etc/letsencrypt/live/stephen-hellicar.com/privkey.pem:/etc/letsencrypt/live/stephen-hellicar.com/privkey.pem:ro
        - /etc/letsencrypt/live/stephen-hellicar.com/chain.pem:/etc/letsencrypt/live/stephen-hellicar.com/chain.pem:ro
        - /data/letsencrypt/:/data/letsencrypt/:ro
        - /etc/localtime:/etc/localtime:ro
volumes:
    certs:
        driver: local
    certs-data:
        driver: local

