#!/bin/sh

DIRNAME=$(dirname $0)
FILENAME=${DIRNAME}/docker-compose.yaml
docker run -it --rm \
      -v shellicar_certs:/etc/letsencrypt \
      -v shellicar_certs-data:/data/letsencrypt \
      deliverous/certbot \
      certonly \
      --webroot --webroot-path=/data/letsencrypt \
      -d stephen-hellicar.com -d www.stephen-hellicar.com
docker-compose -f "${FILENAME}" kill -s SIGHUP proxy

