#!/bin/sh

docker run -it --rm \
      -v shellicar_certs:/etc/letsencrypt \
      -v shellicar_certs-data:/data/letsencrypt \
      deliverous/certbot \
      certonly \
      --webroot --webroot-path=/data/letsencrypt \
      -d stephen-hellicar.com -d www.stephen-hellicar.com
./up
